### ISSUE TITLE
Pass all Test Cases

### ISSUE THREAD

**Issue by bitNathan** [bitNathan/ECE46100-phase-2#10]
Inherited code passes 12/20 test cases

In order for the CI to run fully we need to get the code to pass them all (or remove some cases)

**Comment by MadSons** [comment]
@bitNathan Better to first change the output of the ./run test to be of the format they expect below:
```
Total: 10
Passed: 9
Coverage: 90%
9/10 test cases passed. 90% line coverage achieved.
```

This way we don't exit 1 if the test scripts fail. You can use code similar to our phase 1 implementation, Although it may need to be altered.

**Comment by bitNathan** [comment]
Good point, I'll take a look at the formatting as well

**Comment by bitNathan** [comment]
made a different issue for this
