### ISSUE TITLE
Recommend Package

### ISSUE THREAD

**Issue by bitNathan** [bitNathan/ECE46100-phase-2#28]
Support an additional endpoint called “recommend” that takes a text description and produces a top-5 list of packages to consider.
- LLM API such as OpenAI

**Comment by Osan-Omayuku** [comment]
The /recommend endpoint generates a list of up to 5 recommended npm packages based on a user-provided description of their requirements. It uses an LLM (like OpenAI) to interpret the description and suggest relevant packages.
