### ISSUE TITLE
Fraction of Dependencies Metric

### ISSUE THREAD

**Issue by bitNathan** [bitNathan/ECE46100-phase-2#29]
New metric to be added to phase 1 code
The fraction of dependencies that are pinned to at least a specific major+minor version (see phase 2 specs).

**Comment by MadSons** [comment]
The fraction of dependencies that are pinned to at least a specific
major+minor version, e.g., version 2.3.X of the dependency. (If a package
has zero dependencies, it should receive a 1.0 rating. Now, suppose a
package has two dependencies, one that is constrained to a particular
major+minor version and another that is not. In this case, one of the two
dependencies satisfies the requisite level of pinning, and so the fraction
of dependencies is 1 in 2 or a score of ½ = 0.5.3

**Comment by MadSons** [comment]
New Metric, should be implemented similarly to the other 5 metrics.

**Comment by Osan-Omayuku** [comment]
- Implemented the script in `run.py` to:
  - Parse `package.json` and `package-lock.json`.
  - Compute individual metrics based on specific criteria.
  - Output a JSON object with metrics and latencies.
- Included sample files for testing and demonstration.

**Comment by MadSons** [comment]
Zinat completed this metric
