### ISSUE TITLE
/package/{id}/rate

### ISSUE THREAD

**Issue by MadSons** [bitNathan/ECE46100-phase-2#39]
/package/{id}/rate:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageRating'
          description: Return the rating. Only use this if each metric was computed
            successfully.
        400:
          description: There is missing field(s) in the PackageID
        403:
          description: Authentication failed due to invalid or missing AuthenticationToken.
        404:
          description: Package does not exist.
        500:
          description: The package rating system choked on at least one of the metrics.
      operationId: PackageRate
      summary: "Get ratings for this package. (BASELINE)"
    parameters:
    - name: id
      schema:
        $ref: '#/components/schemas/PackageID'
      in: path
      required: true
    - name: X-Authorization
      description: ""
      schema:
        $ref: '#/components/schemas/AuthenticationToken'
      in: header
      required: true
      
      
![image](https://github.com/user-attachments/assets/16f9c8ea-e30c-48e6-b6be-7be057e6c3f3)

**Comment by bitNathan** [comment]
completed in a PR
